# Generated by Django 6.1 on 2026-08-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_dashboard.user')),
                ('otp', models.CharField(max_length=10)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'password_resets',
            },
        ),
    ]
